apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    chain: {{ .Values.iotex.chain_id }}
{{ include "iotex.labels" . | indent 4 }}
spec:
  ports:
    - name: {{ .Values.service.rpcPortName }}
      port: {{ .Values.service.rpcPort }}
      targetPort: {{ .Values.service.rpcPortName }}
    - name: {{ .Values.service.p2pPortName }}
      port: {{ .Values.service.p2pPort }}
      targetPort: {{ .Values.service.p2pPortName }}
  selector:
    app.kubernetes.io/name: {{ include "iotex.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
